name: Python Unit Testing via Tox

on:
  workflow_call:
    inputs:
      python:
        required: false
        type: string
        default: "3.10"
      platform:
        required: false
        type: string
        default: "ubuntu-latest"

jobs:
  test:
    runs-on: ${{ inputs.platform }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python }}
      
      - name: Install dependencies
        run: |
          pip install .
          pip install tox

      - name: Run tests
        run: |
          tox
