name: Unit Testing

on:
  workflow_call:


jobs:
  test:
    strategy:
      matrix:
        python:
        - "3.7"  # oldest Python supported by PSF
        - "3.10"  # newest Python that is stable
        platform:
        - ubuntu-latest
        # - macos-latest
        - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      
      - name: Install dependencies
        run: |
          pip install .
          pip install tox

      - name: Run tests
        run: |
          tox
